### ISSUE TITLE
Swap Channels for Sky SD

### ISSUE THREAD

**Issue by krisawatson** [oe-alliance/oe-alliance-plugins#119]
The swap channels work for Sky HD but don't work for Sky SD.  I would love this feature for Sky SD also

**Comment by AbuBaniaz** [comment]
For swap to take effect, the target channel must exist and must also be an HD channel.This applies to both HD and SD regions.

**Comment by kriswatson** [comment]
When I scan SD regions the autobouquetsmanager always uses the default SD channels I have to manually change the SD channels with their equivalent HD versions.  All the ones listed under the <swapchannels> in sat_282_sky_uk.xml tag are the ones I would swap out.

**Comment by AbuBaniaz** [comment]
ABM works exactly as you say it should work. You should not have to manually swap channels. I suspect this is a setup issue. Perhaps "swap channels" not enabled?

Please start a thread on WOS. Attach your debug logs as per this thread. http://www.world-of-satellite.com/showthread.php?44783-ABM-support-questions
