### ISSUE TITLE
Change Multitranscoding to old one with port 8002

### ISSUE THREAD

**Issue by witteschnitte** [oe-alliance/oe-alliance-plugins#120]
Hi great work guys in this Software.

I just habe a little Problem With the new multitranscoding.
In the past i can give a port an the STB will transcode.
The New settings may be nice but i have problems on kodi.
Here i cant set the streaming parameters.
Is there a way to reinstall the port based transcoding setup in my atemio nemesis?

Kind regard 
Felix

**Comment by Schimmelreiter** [comment]
Did Atemio ever have a port based transcoding?

**Comment by atvcaptain** [comment]
atemio use same like xtrend and mutant port 8001, and works fine

**Comment by witteschnitte** [comment]
In the past port based transcoding did work. In new it changed to multitranscoding.with 8001 and additional parameters. I want the way back and use the portbased transcoding but i dont know how.

**Comment by atvcaptain** [comment]
not possible atemeo change drivers only 8001 works
