### ISSUE TITLE
Russian providers

### ISSUE THREAD

**Issue by Dima73** [oe-alliance/oe-alliance-plugins#125]
How to add Russian providers?
sat 
36(ntv+,trikolor tv)
56(ntv+,trikolor tv)
75(raduga)
85.2(kontinent)

**Comment by Huevos** [comment]
Do you mean how can Russian providers be added to AutoBouquetMaker?

**Comment by Dima73** [comment]
yes

**Comment by Huevos** [comment]
http://www.world-of-satellite.com/showthread.php?48826-Russian-providers&p=380900&viewfull=1#post380900

**Comment by RobvanderDoes** [comment]
Can we close this issue? When required/wanted assistance can be provided via the link above.
