### ISSUE TITLE
[AutoBouquetsMaker]  Turksat 42.0E providers

### ISSUE THREAD

**Issue by sunder67** [oe-alliance/oe-alliance-plugins#126]
Turksat providers

42.0E  Tivibu
42.0E  D-Smart
42.0E  Filbox
42.0E  Digiturk

http://www.lyngsat.com/packages/europe.html

**Comment by AbuBaniaz** [comment]
Can you check D-Smart is working for you please?

**Comment by sunder67** [comment]
D-smart working

**Comment by RobvanderDoes** [comment]
Can we close this issue?

**Comment by RobvanderDoes** [comment]
15 months old issue without any update, so I presume we shoul close it.

**Comment by AbuBaniaz** [comment]
Please start thread on WOS forum if you need to. Attach debug logs showing ABM execution.
