### ISSUE TITLE
AutoBouquetsMaker All (tv) Problem

### ISSUE THREAD

**Issue by gmanpanthro** [oe-alliance/oe-alliance-plugins#127]
When region is set to Scottish ... custom and also swap is enabled, then BBC Two Scotland is being placed in the wrong position in the EPG. 

In Scotland the EPG on SKY HD is as follows

101 BBC Scotland HD
102 BBC Two Scotland
103 STV HD
...
141 BBC Scotland
142 BBC Two HD

But on file userbouquet.abm.sat_282_sky_uk.main.tv in Scotland you have it set up wrong as youve got it as follows

101 BBC Scotland HD
102 BBC Two HD
103 STV HD
...
141 BBC Scotland
142 BBC Two Scotland

If you could possibly swap the channels 102 and 142 around for Scottish users who have swap option activated on your next update then we would be eternally grateful.

Thanks,

Gordon Wilson

**Comment by AbuBaniaz** [comment]
The "custom region" is uses SD receiver numbering.

Swaps will only work if both channels exist and the target is in HD.

You are basically asking is to disable swap for those two channels.

**Comment by gmanpanthro** [comment]
But surely the fact that there isnt a BBC Two Scotland HD channel (only the English version is available in HD) then why is ABM swapping 2 completely different channels? The service names arent the same so why does it swap in that instance?

**Comment by AbuBaniaz** [comment]
You get the same question for the ITV  as well as BBC One chanenls. Not every region has an equivalent HD chanenl braidcasting teh same content. If you take it away you will get complaints from others.

For instance, at the moment on BBC Two Scotland, Later with Jools Holland is being brodcast. Same program as on BBC Two HD.

I am afraid this is case where you cannot please everyone.

You can use the custom mix feature if you want to swap only the channels you want. To keep things simple, do not use the swap feature. Custom files are not touched during ABM updates, so your preferances will be maintained. You can add the file to your list of backup files too.

**Comment by gmanpanthro** [comment]
Ah that sounds like i could do that - but ive only had my zgemma for 1 week so still quite an amateur with all the menus and settings. 

Could u explain how do i create a custom file?

Thanks

**Comment by AbuBaniaz** [comment]
Please seek assistance from your manufacturer image maker.
