### ISSUE TITLE
[AutoBouquetsMaker] Enhancement proposal

### ISSUE THREAD

**Issue by thatfellow** [oe-alliance/oe-alliance-plugins#13]
Great plugin guys.

I just have a suggestion/request.

Is there any way (Apart from doing it manually each time) to have the likes of ITV1,2,3,4,+1's, Channel 5 etc in the Entertainment Bouquets after I scan Sly IRE? Every time I scan I have to scan the Sly Ireland for the Irish Channels & Sly UK for the channels above.  Similarly for adding Setanta to the UK Sports Bouquets..  I understand after talking to pheonix that the bouquets are based on the slybox bouquet.  I know if you went on requests, this would be a never ending job so maybe some options can be added to the plugin itself to allow channel swapping post scan.

I have seen similar requests for these channel swaps with ABM all over the net.

Again, top class work by the oe-alliance team and I would have no problem helping with testing if you needed any more testers..

**Comment by AbuBaniaz** [comment]
custom-lcn has been there for a while. from Apollo 127, you can now enable non-indexed channels too.

**Comment by AbuBaniaz** [comment]
You can use the custom mix option to merge channels from one provider into another.
Please refer to readme file for more details
