### ISSUE TITLE
Blindscan/KU or C band 

### ISSUE THREAD

**Issue by Dima73** [oe-alliance/oe-alliance-plugins#133]
this satellite need KU band,but fist frequency is C band 

<sat name="Astra 4A/SES 5 (4.9E)" flags="0" position="49"
		<transponder frequency="3644000"
Now start / stop flow rate of 4 digits and should be five.

**Comment by Huevos** [comment]
Not sure what you mean. Ku position is 4.8E. It has been like that a long time. Years. And other teams have requested that postion does not change, otherwise settings will break.

**Comment by Dima73** [comment]
please see first/last frequency
	<sat name="Astra 4A/SES 5 (4.9E)" flags="0" position="49">
		<transponder frequency="3644000" symbol_rate="1300000" polarization="0" fec_inner="4" system="1" modulation="1"/>
		<transponder frequency="3678000" symbol_rate="1682000" polarization="0" fec_inner="7" system="1" modulation="1"/>
		<transponder frequency="3680000" symbol_rate="1517000" polarization="0" fec_inner="7" system="1" modulation="1"/>
		<transponder frequency="3684000" symbol_rate="1683000" polarization="0" fec_inner="7" system="1" modulation="1"/>
		<transponder frequency="3688000" symbol_rate="1683000" polarization="0" fec_inner="7" system="1" modulation="1"/>
		<transponder frequency="3731000" symbol_rate="1600000" polarization="1" fec_inner="1" system="1" modulation="1"/>
		<transponder frequency="3843000" symbol_rate="1055000" polarization="1" fec_inner="9" system="1" modulation="1"/>
		<transponder frequency="3844000" symbol_rate="1162000" polarization="1" fec_inner="3" system="1" modulation="1"/>
		<transponder frequency="3850000" symbol_rate="3600000" polarization="1" fec_inner="2" system="1" modulation="1"/>
		<transponder frequency="3857000" symbol_rate="1520000" polarization="1" fec_inner="7" system="1" modulation="1"/>
		<transponder frequency="3863000" symbol_rate="1130000" polarization="1" fec_inner="4" system="1" modulation="1"/>
		<transponder frequency="3865000" symbol_rate="1547000" polarization="1" fec_inner="2" system="1" modulation="1"/>
		<transponder frequency="3867000" symbol_rate="1400000" polarization="1" fec_inner="2" system="1" modulation="1"/>
		<transponder frequency="3868000" symbol_rate="1203000" polarization="1" fec_inner="4" system="1" modulation="1"/>
		<transponder frequency="3870000" symbol_rate="1550000" polarization="1" fec_inner="2" system="1" modulation="1"/>
		<transponder frequency="3875000" symbol_rate="6200000" polarization="1" fec_inner="2" system="1" modulation="1"/>
		<transponder frequency="3924000" symbol_rate="19000000" polarization="0" fec_inner="2" system="1" modulation="1"/>
		<transponder frequency="4100000" symbol_rate="3254000" polarization="0" fec_inner="2" system="0" modulation="1"/>
		<transponder frequency="11265000" symbol_rate="30000000" polarization="0" fec_inner="3" system="1" modulation="2"/>
		<transponder frequency="11265000" symbol_rate="30000000" polarization="1" fec_inner="3" system="1" modulation="2"/>

**Comment by Huevos** [comment]
Where did you get that file? It is wrong. Should only contain one band per position.

Download the correct file here: https://github.com/oe-alliance/oe-alliance-tuxbox-common/tree/master/src

**Comment by Dima73** [comment]
this http://satellites-xml.eu/ only Astra 4A/SES 5 (4.9E)
Many users use this site.
They told me and wrote about the impossibility of entering the fifth digit.
It is necessary to fix it.

**Comment by Dima73** [comment]
Huevos 
I understood.
Users download  http://satellites-xml.eu/  the wrong file(need set  'Split different band transponder ').
the matter is closed.
Another small question, what dual tuner VU + does not work with the blind scan?
Sorry, I forgot  name.

**Comment by Huevos** [comment]
Please do not use that site.

Use http://satellites-xml.org/

This site is compatible with all OE-A images and settings.

But even better just download the current OE-A satellites.xml from https://github.com/oe-alliance/oe-alliance-tuxbox-common/tree/master/src

**Comment by RobvanderDoes** [comment]
Maybe there is a misunderstanding?
The position 4.8E (position="48") refers to the Ku-band, while the position 4.8E (position="49") refers to the C-band. This is standard practice, also for other images like PLi.
