### ISSUE TITLE
[AutoBouquetsMaker] Cannot open shared object file dvbreader.so

### ISSUE THREAD

**Issue by rallymoose** [oe-alliance/oe-alliance-plugins#14]
I have tried installing this plugin on my box and it cannot read the file dvbreader.so
I have also tried the AutoBouquets plugin and that does work...
All other files seems to be ok, except dvbreader.so...
I have no idea what is causing the problem... I have a GM media Triplex (mipsel device) and have tested both HDMU and PKT images based on openpli and both of them shows the same error...
Would it be possible for someone to compile the dvbreader.so as a static library (maybe  that works better?)... I do not have the knowledge to compile it myself (unless its windows with visual studio only)...

Picture of the error that comes up when i go into the plugins menu:
![error](https://f.cloud.github.com/assets/5115063/873434/864582c6-f877-11e2-8463-babc67dd7c9a.png)

**Comment by AbuBaniaz** [comment]
ABM works on SH4 receivers. I believe the plugin is available in PKT images
