### ISSUE TITLE
Add XMLTVIMPORT / CROSSEPG plugin

### ISSUE THREAD

**Issue by Neustradamus** [oe-alliance/oe-alliance-plugins#150]
Hi all,

Can you add the XMLTVIMPORT / CROSSEPG plugin?

http://www.clouditaly.tk/xmltv-import/
http://www.rytec.be/
https://xtream-codes.com/forum/?app=forums&module=forums&controller=topic&id=3344

Thanks in advance.

Regards,

Neustradamus

**Comment by AbuBaniaz** [comment]
On OE-A images, it is called EPG-importer. Install it if it is not installed by default in your image.
