### ISSUE TITLE
ADD SYSTEMTIME plugin

### ISSUE THREAD

**Issue by Neustradamus** [oe-alliance/oe-alliance-plugins#151]
Hi all,

Can you add the SYSTEMTIME plugin?

Example on https://xtream-codes.com/forum/?app=forums&module=forums&controller=topic&id=3344

Thanks in advance.

Regards,

Neustradamus

**Comment by RobvanderDoes** [comment]
You'll find that most OE-A images have and always had an embedded option for setting & updating system time.

**Comment by Neustradamus** [comment]
But there is not possibility to choice options, example the NTP server...

**Comment by RobvanderDoes** [comment]
That will depend on the image used, see e.g. what has been embedded in ViX:
![ts 01](https://cloud.githubusercontent.com/assets/1040294/18034847/82bf975c-6d47-11e6-8d5c-14abf8018637.jpg)

Other images may have different options. IMHO it's better to ask your image builder to enhance his image (if required) then adding again a plugin.

**Comment by Neustradamus** [comment]
I try several images, and yes, it is different.
Why it is not a default for all?

**Comment by RobvanderDoes** [comment]
If all images would be the same, we wouldn't need different images :)
Just ask your team.

**Comment by RobvanderDoes** [comment]
Can we close this issue?

**Comment by AbuBaniaz** [comment]
Please re-open if needed.
