### ISSUE TITLE
[AutoBouquetsMaker] Tvsat provider works on alternate days

### ISSUE THREAD

**Issue by margy82** [oe-alliance/oe-alliance-plugins#23]
Hi guys, I found a problem with tvsat provider, it works on alternate days. For example yesterday it found all channels but today some channels are missing and in particular I miss rai channels like rai uno, rai due, rai tre, rai 4 etc.
I Always have this kind of problem only on tvsat provider.
No errors on log
Any suggestion?

**Comment by AbuBaniaz** [comment]
Tivusat was worked on by Huevos recently. Please check again

**Comment by AbuBaniaz** [comment]
I am closing this now. Please reporta gain if issue persists
