### ISSUE TITLE
[AutoBouquetsMaker]  CBBC HD & CBeebies HD not available in Irish bouquets

### ISSUE THREAD

**Issue by thatfellow** [oe-alliance/oe-alliance-plugins#30]
Can the ROI bouquets be updated to include the HD versions of these channels?

**Comment by AbuBaniaz** [comment]
From Apollo 127, enable non-indexed channels.

**Comment by AbuBaniaz** [comment]
You can also employ the various customistaion features to mix chanenls from different providers.
