### ISSUE TITLE
lcd4linux: line 182: Error as default defined

### ISSUE THREAD

**Issue by HarryHase11** [oe-alliance/oe-alliance-plugins#316]
line 182: html += "Default is: 127. 192.168. 172. 10.\n" - absolut sensless
better html += "Default is: *\n"

Line 182 prevent to open lcd4linux website

**Comment by atvcaptain** [comment]
ah da hat jemand seine private config eingebaut und vergessen nas und ip zu entfernen sind nun alles raus
