### ISSUE TITLE
Attribute error before scanning

### ISSUE THREAD

**Issue by MCelliotG** [oe-alliance/oe-alliance-plugins#328]
Gives green screen once pressing the green button, HD51 OpenATV 6.3 latest
`20:01:51.8321 [ E ] gdi/gpixmap.cpp:216 gSurface [gSurface] ERROR: accelAlloc failed
20:01:51.8389 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-18 20:01:51+0300 [-] [SCREENNAME]  MisPlsLcnScan
20:01:52.0403 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-18 20:01:52+0300 [-] [MisPlsLcnScan][getFrontend] searching for available tuner
20:01:52.0413 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-18 20:01:52+0300 [-] Traceback (most recent call last):
20:01:52.0418 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-18 20:01:52+0300 [-]   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/MisPlsLcnScan/MisPlsLcnScan.py", line 190, in getFrontend
20:01:52.0429 { E } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2019-05-18 20:01:52+0300 [-] AttributeError: 'NIM' object has no attribute 'isFBCLink'
20:01:52.0431 [ E ] python/python.cpp:210 call [ePyObject] (PyObject_CallObject(<bound method MisPlsLcnScan.getFrontend of <class 'Plugins.SystemPlugins.MisPlsLcnScan.MisPlsLcnScan.MisPlsLcnScan'>>,()) failed)`

**Comment by Huevos** [comment]
Is this just a one off thing or does it happen 100% of the time. 6.3 does have that attribute.

**Comment by atvcaptain** [comment]
i have add today

**Comment by Huevos** [comment]
Thanks.

**Comment by MCelliotG** [comment]
Fixed today! Time to skin it now! Thanks!

**Comment by MCelliotG** [comment]
Please regenerate the .po files for MISPLSScan or a .pot file, some strings are not corresponding thus cannot be translated.
Example with Found %d transponders
![mispls](https://user-images.githubusercontent.com/10141510/57985779-c5cfc100-7a75-11e9-927b-527e27f5594a.jpg)

**Comment by Huevos** [comment]
Ok, give me a few minutes to rebuild it. I can't get PR2 script working here on my windows laptop. No idea what I am doing wrong.

**Comment by Huevos** [comment]
Ok. Done now.

**Comment by MCelliotG** [comment]
The .po generation is now OK on incomplete strings, however there are some more to be tweaked inside the code
For instance
```
self["action"].setText**(_(**"Tuning %s MHz, IS %s") % (str(self.transpondercurrent.frequency/1000), str(self.transpondercurrent.is_id)))
self["status"].setText(ngettext**(**"Found %d transponder", "Found %d transponders", len(self.transponders_correct_onid)) % len(self.transponders_correct_onid))
```
The "Found %d transponder" string misses the required (_( in order to be translatable, it's OK in the po, but needs to be tweaked.
Same as Italia MIS etc.

**Comment by Huevos** [comment]
Can you submit a pull request with the changes you require please.

**Comment by MCelliotG** [comment]
I'll test the changes and then I'll do if they're OK. Please push the translation update if you like!

**Comment by Huevos** [comment]
Did this get solved?

**Comment by MCelliotG** [comment]
The green screen yes, the translation of these three strings no, and honestly I can't find any error in the code either (although I'm terrible at it).
![mispls](https://user-images.githubusercontent.com/10141510/58375415-1c983780-7f5b-11e9-8a47-b0a7d320ccf3.jpg)
BTW any plans to extend LCN scan to DVB-T/T2 as well?

**Comment by AbuBaniaz** [comment]
If the SI tables are fine, would be better to add to provider to AutoBouquetsMaker

**Comment by Huevos** [comment]
Does your terrestrial television have LCNs? Can you get a full transport stream recording?

Both ABM and TerrestrialScan plugins do LCN scans of terrestrial where LCNs are present. Currently ABM can scan UK, Netherlands and Ireland terrestrial and order by LCN.

**Comment by Huevos** [comment]
This should sort out the translation of the provider names. https://github.com/oe-alliance/oe-alliance-plugins/commit/66b2db32451265c981ac1f07000d2a91d99f83cc

Not sure the cause of the other problem yet.
