### ISSUE TITLE
is blindscan realizable under sr1000 ?

### ISSUE THREAD

**Issue by Suedschwede66** [oe-alliance/oe-alliance-plugins#356]
Hello everybody,
I have an Octagon SF8008 where the tuner from sr 100 - sr 80000 works. Now my question, can you extend the BS plugin so the transponder can be found under sr 1000?

**Comment by Huevos** [comment]
No, this is not being played with at the risk of instability on other STBs.

If you want this change modify the .py file and add the file to your own STB.

BTW, there are no proper DTH television channels with symbol rates below 1000.
