### ISSUE TITLE
Blind scan with circular Ku-Band LNB is not possible

### ISSUE THREAD

**Issue by Suedschwede66** [oe-alliance/oe-alliance-plugins#363]
Today I wanted to do a blind scan on 56.0E Express and found that this is neither possible with the circular tuner setting nor with user-defined.
According to the log, all transponders found are read in, but it is always indicated that nothing was found. There is probably an error in the BS plugin.
With manual scan, 111 channels are found with the same tuner settings Circular and User-defined.
[blindscan-debug.log](https://github.com/oe-alliance/oe-alliance-plugins/files/4397844/blindscan-debug.log)

**Comment by Huevos** [comment]
Using which STB?

**Comment by Suedschwede66** [comment]
Octagon SF8008 with OpenATV6.4

**Comment by Huevos** [comment]
What are your grounds for blaming the plugin? Have you investigated this fully? What are your findings?

**Comment by Suedschwede66** [comment]
As you can see in the debug log, transponders found are just not written into Blindscan.xml, then no channels can be found either.

**Comment by Huevos** [comment]
It would help if you provided a debug log without all the noise. They are not written because they are out of range. 

```
19:56:22.1836 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-03-23 19:56:22+0100 [-] [Blindscan][blindscanContainerClose] cnt: 10 , data: ['OK', 'VERTICAL', '11053000', '27501000', 'DVB-S2', 'INVERSION_ON', 'PILOT_OFF', 'FEC_3_4', '8PSK', 'ROLLOFF_35']
19:56:22.1842 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-03-23 19:56:22+0100 [-] [Blindscan][dataIsGood] Data returned by the binary is not good...
19:56:22.1847 {   } /usr/lib/python2.7/site-packages/twisted/python/util.py:815 untilConcludes 2020-03-23 19:56:22+0100 [-] 	Data: Frequency [11053000], Symbol rate [27501000]

```

Before starting to point the finger let's start thorough debugging. And please remember not everyone has access to the hardware or satellites needed to provide debug for this.

**Comment by Suedschwede66** [comment]
Here are the settings of the tuner and blind scan
![Bildschirmfoto vom 2020-03-28 21-58-34](https://user-images.githubusercontent.com/56753772/77833808-65eb8180-7140-11ea-848a-6c4445aef6b5.png)
![Bildschirmfoto vom 2020-03-28 22-03-27](https://user-images.githubusercontent.com/56753772/77833812-6f74e980-7140-11ea-90d9-6a32fa19f5d2.png)
![Bildschirmfoto vom 2020-03-28 22-04-43](https://user-images.githubusercontent.com/56753772/77833831-7f8cc900-7140-11ea-9136-786513cbe508.png)

**Comment by Suedschwede66** [comment]
To rule out an error tomorrow I will test and report using the same setup on an Edision Os Mio4k.

**Comment by Huevos** [comment]
Tested on Mio 4K+. User defined works fine.

Let's make this easier. Set up a tuner as follows (on a dish with a universal LNB) that you can scan 19.2E.

LOF/L = 10600
LOF/H = 10600
Threshold = 10600
Voltage mode = Polarization
Tone mode = yes.

Then scan 19.2E.
Try with Edision and Octagon so we can compare the output.

**Comment by Suedschwede66** [comment]
Universal LNB in the Ku band is ok, C band R / L and H / V is also ok with the Octagon, I use that every day, there have never been any problems.
If I use a converted universal LNB with dielectric plate (Inverto Black Ultra) with universal tuner settings, the blindscan on 56.0E also works correctly.
It works with universal tuner settings, even with the original circular LNB of the blindscan to 56.0E, only then the transponders found are offset with the frequencies a lot.
With all the variants just described, the blindscan works perfectly and a blindscan.xml is written with each scan.
Only the blindscan with the original circular KU band LNB (in the appendix) does not work, neither with user-defined / circular tuner settings.
[GT-SCIR40M.pdf](https://github.com/oe-alliance/oe-alliance-plugins/files/4398436/GT-SCIR40M.pdf)

**Comment by Suedschwede66** [comment]
With the Edision Os Mio4k, the blind scan with the same settings as the Octagon SF8008 is fine. So there seems to be a bug with the Octagon SF8008.
![screenshot_20200329124432](https://user-images.githubusercontent.com/56753772/77847305-7e997d00-71bc-11ea-8779-67eb1514bc3e.jpg)
![screenshot_20200329124734](https://user-images.githubusercontent.com/56753772/77847307-8527f480-71bc-11ea-8f05-2f8d9aec0b88.jpg)

**Comment by Huevos** [comment]
Octagon follows a different code path in a couple of places in the plugin. I will look at that first. Anyway some thing strange has happened because we had a private test group 12-18 months ago and all was working fine on SF8008.

**Comment by Suedschwede66** [comment]
Great that you stay tuned and sacrifice your time, thanks.

**Comment by Huevos** [comment]
Please try this...

https://github.com/oe-alliance/oe-alliance-plugins/commit/a3995e6ad41e66bfe2ae1fbe4938dc7d05af7703

**Comment by Suedschwede66** [comment]
Great, with this change it works wonderfully, thanks.
![screenshot_20200330001344](https://user-images.githubusercontent.com/56753772/77862489-ee8b2000-721b-11ea-98cc-ea0a28afa753.jpg)
![screenshot_20200330001734](https://user-images.githubusercontent.com/56753772/77862492-f5199780-721b-11ea-93be-bbdd41c84f76.jpg)

**Comment by Suedschwede66** [comment]
All scan combinations work, linear KU / C-Band and circular KU / C-Band, good job.
![circ_c_bs_scan_57E](https://user-images.githubusercontent.com/56753772/77864156-6743a980-7227-11ea-8dd8-8c88bb1ecb1f.jpg)
![circ_c_bs_found_57E](https://user-images.githubusercontent.com/56753772/77864165-77f41f80-7227-11ea-9141-2b4a04318e55.jpg)
![lin_c_bs_scan_38E](https://user-images.githubusercontent.com/56753772/77864173-83dfe180-7227-11ea-91c5-fc261b1c2e39.jpg)
![lin_c_bs_found_38E](https://user-images.githubusercontent.com/56753772/77864190-8e01e000-7227-11ea-9b64-386aafbfc9a7.jpg)
![lin_ku_bs_scan_33E](https://user-images.githubusercontent.com/56753772/77864195-95c18480-7227-11ea-8a16-b045ac76782e.jpg)
![lin_ku_bs_found_33E](https://user-images.githubusercontent.com/56753772/77864206-9f4aec80-7227-11ea-8f4c-19540af15efb.jpg)

**Comment by Suedschwede66** [comment]
Now that everything works again as it should I close here, thanks again for the quick help.
