### ISSUE TITLE
Blindscan Extended C-Band Setup Problem

### ISSUE THREAD

**Issue by Suedschwede66** [oe-alliance/oe-alliance-plugins#388]
Hi there,

I am creating a ticket for a DX'er who has problems with an extended C-band LNB for the 4.5-4.8 GHz.
I hope that's understandable what the problem is.

> Zitat Satfaca
> I have a request for the developers ...
> There is a big problem for us who want to use "unconventional" C-band LNBs - such as extended or hybrid LNBs whose LOF is not 5150 MHz. In this case we have to use the "Custom" option to set the LOF, but as a result the frequency scan range no longer coincides with reality.
> Can this be fixed in the foreseeable future please?
![C1](https://user-images.githubusercontent.com/56753772/103456209-46e3d680-4cf4-11eb-8750-667a10b50668.jpg)
![C2](https://user-images.githubusercontent.com/56753772/103456212-4ba88a80-4cf4-11eb-8195-2aded097c82f.jpg)
![C3](https://user-images.githubusercontent.com/56753772/103456214-506d3e80-4cf4-11eb-949c-0652e525ea9d.jpg)

**Comment by Suedschwede66** [comment]
It is exactly about this LNB here in the picture.
![Norsat_8000RI_b](https://user-images.githubusercontent.com/56753772/103465496-4bcc7880-4d3c-11eb-8d77-e3107ad3ca9c.jpg)

**Comment by Huevos** [comment]
You have LNB inversion set wrong.

**Comment by Suedschwede66** [comment]
Thanks, that was it, so just a wrong setting and no problem from the BS

![normal](https://user-images.githubusercontent.com/56753772/103533023-a96fda80-4e8c-11eb-953a-bab6fabe6f76.jpg)
![invertet](https://user-images.githubusercontent.com/56753772/103533038-af65bb80-4e8c-11eb-8d70-5338f4b2d2fd.jpg)
