### ISSUE TITLE
Ultimo4k running OpenBh 5.2.005 ( hangs )

### ISSUE THREAD

**Issue by nunigaia** [oe-alliance/oe-alliance-plugins#691]
After severall hours +/- 12hours STB´s hangs when using LCD4Linux. This happens also with OpenVIX 6.3.005. Should happen too, with other images that uses python 3.11 as OpenATV 7.2
After this is almost impossible to zap, or navigate through the whole panels system to set anything, where pushing any button on the RCU, brings the spinner ( so it must be any background job running, regarding LCD4Linux plugin ).

Log:

Traceback (most recent call last):
File "/usr/lib/enigma2/python/Plugins/Extensions/LCD4linux/plugin.py", line 4833, in run
para[0](para[1], para[2], para[3])
File "/usr/lib/enigma2/python/Plugins/Extensions/LCD4linux/plugin.py", line 11623, in putExternalIP
line = Code_utf8(ConfigText.decode().replace(' ', ''))
^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'

Note: It happens also, with Duo4KSE, Uno4KSE, Duo4K ( that I own ).

best regards
nunigaia

**Comment by MrServo** [comment]
I'll have an eye on this...

**Comment by MrServo** [comment]
Done!  You can close this issue if OK... ;)
regards......Mr.Servo

**Comment by nunigaia** [comment]
> Done! You can close this issue if OK... ;) regards......Mr.Servo

I have to wait ( just testing it ), the errors has gone, although I have to wait severall hours, to check the zapping when using "LCD4Linux".

As you know, I reported that the zapping or even navigating through the MENUS was not OK. 

If the issue persists we can call @atvcaptain help to fix it ;)

Thanks and wait please,

best regards
nunigaia

**Comment by jbleyel** [comment]
Please try again with the latest update from today.

**Comment by AbuBaniaz** [comment]
@nunigaia 
Is this issue resolved?

**Comment by MrServo** [comment]
Yes, the memory-leak-error have been found and the problem was completely solved within LCD4linux V5.0-r17!
Issue can be closed!
