### ISSUE TITLE
LCD4linux: Wind speed : 2 lines shows N/A

### ISSUE THREAD

**Issue by Orlandoxx** [oe-alliance/oe-alliance-plugins#695]
Hello,
LCD4linux: when you select "Weather Wind Info Lines" = 2 lines, it shows N/A.

![Weather_no_wind_values](https://user-images.githubusercontent.com/95180049/229490152-2664f321-176e-4654-885a-2fff338abd8d.png)

**Comment by MrServo** [comment]
I have tested it with all four services and I can't reproduce this mistake, everything works perfect...
Which weatherservice do you use (mistake for all services or for only one)?

**Comment by Orlandoxx** [comment]
MSN

**Comment by Orlandoxx** [comment]
Hello,

obtained API-key of Openweathermap
When using it I get:

 "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."

Is it wrong ?:
http://api.openweathermap.org/data/2.5/onecall?&lon=27.873&lat=62.3153&units=metric&exclude=hourly,minutely,current&lang=fi&appid=xxxxxxxxxxxxxxx

Should it be ?:
http://api.openweathermap.org/data/2.5/forecast?&lon=27.873&lat=62.3153&units=metric&exclude=hourly,minutely,current&lang=fi&appid=xxxxxxxxxxxxxxx

xxxxxxxxxxxxxxx is my API-key.

Then I get:

[forecast.zip](https://github.com/oe-alliance/oe-alliance-plugins/files/11169355/forecast.zip)

**Comment by MrServo** [comment]
Both of your OWM-URLs works perfectly! Sure, both URL sends different JSONs and LCD4linux evaluates only the older method that works even with years old API-Keys...
![grafik](https://user-images.githubusercontent.com/57303913/230390287-b05b53c0-1a9b-46b0-ae7f-2b0b44a75049.png)
![grafik](https://user-images.githubusercontent.com/57303913/230390344-ea618288-7819-41a1-877d-e8f4d5e3c3d7.png)
**Sorry, but I can't find any mistakes, neither with MSN nor OpenMeteo nor OWM...**

BTW: LCD4linux uses a very similar code that was just developed for Metrix (skin of openATV) and for OAWeater (supports external skins like BlueAccents or Kraven). The weather programming of LCD4linux followed this new code after it was successfully tested on hundreds of boxes. This is of course no reason, but this and the knowledge that only you have problems with LCD4linux gives a clue if it is really LCD4linux.
So I have no idea what is going wrong with your configuration...

**Comment by MrServo** [comment]
Moment please, I have an idea and I have to verify this... There is hope ;)

**Comment by MrServo** [comment]
DONE! Was much more easier as espected: The problem could occur when, for example, there was a calm and therefore no wind direction at all. This also explains why it then occurred with all weather services...
Thanks for the hint!

**Comment by Orlandoxx** [comment]
Very good, thank you. Just let me know if more testing is needed in the future. I'm also a OpenViX beta tester.

**Comment by Orlandoxx** [comment]
Now it looks okay (here is no wind at all at the moment) !

![dpf](https://user-images.githubusercontent.com/95180049/230431520-3ce36474-dbf2-4a73-8a33-5b2d7145c542.png)

**Comment by Orlandoxx** [comment]
I have done more testing and the problem seems be wind seed unit = m/s, then you have 0, N/A, N/A, but if you have the wind speed unit km/h, then it is okay. @MrServo can you check that ?

![Helsinki_ms](https://user-images.githubusercontent.com/95180049/230438650-73e0e64f-3211-457f-9088-ed529145f3f8.png)

![Helsinki_kmh](https://user-images.githubusercontent.com/95180049/230438712-f266a546-a0f1-40f9-b1ee-3ab0a666a088.png)

**Comment by Orlandoxx** [comment]
Varkaus, when wind speed unit is km/h is also OK.

![Varkaus_kmh](https://user-images.githubusercontent.com/95180049/230439976-a6088485-4c80-4497-abf8-f87d520b059b.png)

**Comment by Orlandoxx** [comment]
Hello @MrServo 

if add this line

self.WDay[ConfigWWW]["Wind"] = "%s m/s %s" % (str(int(round(current.get("windSpd", 0) / 3.6 * 100)) / 100), getDirection(current.get("windDir", 0)))

before line number 9978 then I have wind speed with 2 decimals m/s.

![ms_fixed_MSN](https://user-images.githubusercontent.com/95180049/230461415-7c2e7fb6-f387-4114-8d17-ef6417420af6.png)

**Comment by MrServo** [comment]
DONE & tested for all 4 weather services with wind speed units 'km/h' and 'm/s'. Thank you for your detailed analysing and reporting!!!!
Regards and Happy Easter...

**Comment by Orlandoxx** [comment]
Thank you very much! This issue can be closed now!
