### ISSUE TITLE
Bluescreen since last change in tmdb plugin.py

### ISSUE THREAD

**Issue by willy014** [oe-alliance/oe-alliance-plugins#718]
last commit in tmdb plugin.py generate bluescreen in some EPG screens.
But only at some Boxes for example Vu or Octagon SX88
" 8:22:42.5673 TypeError: EPGSelection__init__() got an unexpected keyword argument 'EPGtype' "

**Comment by jbleyel** [comment]
This is the fist step but not finished.

https://github.com/oe-alliance/oe-alliance-plugins/pull/719

**Comment by jbleyel** [comment]
fixed
