### ISSUE TITLE
LCD4linux

### ISSUE THREAD

**Issue by Marchella1983** [oe-alliance/oe-alliance-plugins#781]
Good afternoon! Dear developers please add these improvements to the plugin oe-alliance/oe-alliance-plugins@ce2c6e7 to the plugin...

**Comment by Marchella1983** [comment]
Yes, but not all of them.

There is one small problem with viewing IPtv as media and there is a fix for it.
https://github.com/oe-alliance/oe-alliance-plugins/pull/387/commits/2afb05d1c234b6e1d6fc9e722897faa9affb4aa8

please make changes to that too.

**Comment by MrServo** [comment]
Done! I hope I have now transferred all the suggested changes correctly...

**Comment by Marchella1983** [comment]
one more correction
`If self.Lpath and self.Lpath.startswith("http") and self.Llength and self.Llength[0] == -1:`

replace with
`if self.Lpath and self.Lpath.startswith((("http", "https")) and self.Llength and self.Llength[0] == -1:`

Tnx @Dorik1972!

**Comment by jbleyel** [comment]
This change makes no difference to me.

**Comment by Marchella1983** [comment]
> This change makes no difference to me.

I'm sorry! It may not matter to you, but it does to us.

Is it a problem for you to correct this part of the code?
https://github.com/oe-alliance/oe-alliance-plugins/blob/1a53f641752e2436c574e4b7b838070cb7e82d87/LCD4linux/src/plugin.py#L14486

**Comment by jbleyel** [comment]
```
>>> Lpath = "https"
>>> Lpath.startswith("http")
True
>>>
```
