### ISSUE TITLE
Controls in the plugin YoutubeTV.

### ISSUE THREAD

**Issue by 68foxboris** [oe-alliance/oe-alliance-plugins#805]
I have a duo4kse and pulse4kmini.There is an application YoutubeTV.Works on both receivers. But the control is on pulse4kmini more familiar than on duo4kse.On duo4kse the red button is mainly used.Press the exit button and immediately exit the plugin.On pulse4kmini the management is adequate.Can this be fixed somehow or not?

**Comment by jbleyel** [comment]
YoutubeTV on VU+ is closed source.
