### ISSUE TITLE
BBC TV programmes failing to download

### ISSUE THREAD

**Issue by fabmini** [oe-alliance/oe-alliance-plugins#90]
As of today I'm no longer able to download BBC TV programmes using Get iPlayer Automator. It takes an age to initialise, and then I get an error that the download has failed (problem unknown, submit bug report etc.). I'm running on OS 10.10.2, GIA version 1.8.5 (1735), through Overplay SmartDNS.
Have tried computer restart, modem restart, GIA restart, nothing's helping. Haven't had problems until today. Still able to access BBC iPlayer website, and BBC radio programmes download fine.

Unfortunately I have no clue how to attach a log file to this message: I have followed the necessary instructions carefully, but according to GitHub a TextEdit file type isn't supported.
I'm a first-time user on this platform, so apologies in advance if I'm doing anything wrong.

**Comment by AbuBaniaz** [comment]
Ondemand does not work for the BBC IPlayer at the moment. Try Kodi Direct
